= Reflexion sobre el futuro
Jose Juan Montiel
2022-03-04
:jbake-type: post
:jbake-tags: life, work, ikigai
:jbake-status: published
:jbake-lang: es
:source-highlighter: prettify
:id: donde-te-ves-4
:icons: font

== Y tras el repaso, toca la reflexión

Llegamos al final del ejercicio, a veces cuesta sacar tiempo para lo que sea. Vivimos en el mundo del ya, venga, rápido... no te pares a pensar... pero bueno, parece que aunque me haya costado casi 2 meses, entre unas cosas y otras, he podido reflexionar, rodándole horas al sueño y a otras cosas.

Y habiendo hecho el recorrido por los acontecimientos pasados, y teniéndolos frescos en la cabeza, puede resultar mas fácil reflexionar sobre lo que tengo por delante.

Recordemos que la pregunta era: ¿donde te ves a los 50? y por tanto ¿que necesitas ir haciendo ahora para poder llegar ahi? Sabemos que la vida es incierta, cualquier sensación de seguridad puede romperse en cualquier momento y obligarte a adaptarte, pero bueno, eso no quita para intentar trazar un plan, y a cambiarlo, si la necesidad te lleva a ello.

A estas alturas, te preguntaría si has tenido tiempo de averiguar todo lo que te he querido mostrar (si querías descubrirlo)... ¿has descubierto mi camino? ¿has pensado en lo que he pensado?... Espero que si, házmelo saber. 

Recuerda, este es https://josejuanmontiel.github.io[**el resultado final**]... o si viniste aquí buscando información sobre mi... puedes descargar mi https://josejuanmontiel.github.io/cv.html[**CV**] 
