= Blog in GitHub Pages with Jbake and Gradle
Jose Juan Montiel
2016-08-25
:jbake-type: post
:jbake-tags: jvm,groovy,blog,github,jbake,gradle
:jbake-status: published
:jbake-lang: en
:source-highlighter: prettify
:id: blog-jbake-gradle
:icons: font

== It's time to start a blog about programming

The truth is that as time passes, you realize that sharing is winning. Some, are given as much before, but although
I already intuited, have had to spend over 10 years in the art of programming to realize. Share is to win,
is to know other opinions, ways of doing things and of course, meet other people... they call networking.

I already had a http://accreativos.blogspot.com.es/[blog] is more a list of things you're finding and take note to
remember, that really a way to share information and comment on it. Then came the
http://twitter.com/accreativos[twitter] but in the end, it is a mixture of retweets, and little original information.

So, why not, a serious blog, like those used to reading these, those where people end up leaving
a lot of comments, those that you add to your RSS reader to be aware of what is said in them,
And if you learn something mounting it, because what else can you ask for.

Therefore, items that will use this blog are:

* English (Spanish)
* GitHub Pages
* AsciiDoctor
* Groovy
* Jbake
* Gradle
* Freemarker (Thymeleaf)
* Discus (Discourse)

We see you in a bit of detail each point.

=== English

The first thing I take advantage of it to improve my English. So, although I write in Spanish, my native language,
publishes in English (and I assume that since I write in Spanish, these also the publicare, and I'll see as attachment).

=== Github Pages

GitHub for some time now began to publish static pages allow for all your projects done. If you are looking for
https://pages.github.com [Github Pages] will see extensive information, besides, many people already using github
tapped to mount functionality for small static sites.

Basically it is that everything that you upload to the branch gh-pages of your github repository, will be visible in the domain
http://username.github.io/repo/file where username is your user github, repo is the name of the repo where these
going up files to the branch gh-pages and file is the file that if an index.html the browser displays,
and the same for css and js with what you already have ready the web.

They also provide a default generator, https://help.github.com/articles/about-github-pages-and-jekyll/[Jekyll]
to generate these static pages from a text in markdown format, but we will not use it,
We see the alternative.

=== AsciiDoctor

We prefer to use something that is between, markdown and latex, and that is called http://asciidoctor.org/[AsciiDoctor] that
true also this http://asciidoctor.org/news/2014/02/04/github-asciidoctor-0.1.4-upgrade-5-things-to-know/[supported]
by GitHub.

=== Groovy

Like my native language is Spanish, my native language is this in Java programming, and as is
learn, and I have a few years playing with groovy, and I will not miss the opportunity to mount the blog using it.
I will tell on another occasion, as I started in this groovy, and what are the places where I learn.

=== Jbake

And we have said that we were not going to use https://jekyllrb.com/[Jekyll] that is done in Ruby, because what we mola is
Groovy;) But we need our written txt in AsciiDoctor be transformed into HTML (or XML we'll see how)
and above all that what we write is inserted in those HTML, we will use http://jbake.org/[Jbake].

=== Gradle

But hey, this needs to be automated, at the end, there are a number of steps, why not use Gradle, as well
http://melix.github.io/blog/2014/02/hosting-jbake-github.html[the creator] of
https://github.com/jbake-org/jbake-gradle-plugin[plugin], it is the perfect combination.

A couple of notes, as it has been somewhat outdated ... http://www.orany.cz/blog/2014/10/17/migrated-to-jbake.html[that
Ornay write time ago] and which faces plugin to upload the pages to the branch, it has also been actualized,
https://plugins.gradle.org/plugin/org.ajoberstar.github-pages[aqui this].

=== Freemarker (Thymeleaf)

And this tool is able to use different templating systems (specifically start with Freemarker, and more
I later migrate to Thymeleaf) to inject the values ​​obtained in asciidoctor txt, along with some
more variables to help build a blogging system that does not have anything envy to Jeklly, Wordpress or
what is put forward.

=== Disqus (Discourse)

But finally, a system without the possibility of blog comments, don't make sense. To do all these i used
https://disqus.com/[Discus] that integrate perfectly with a line (almost). As an option, I will try to migrate to
https://www.discourse.org/[Discourse] but that will come later.

== Extra Ball. Analytics.

As extra ball, remember to add the analitica.

Keep on Groovying!