= Thymeleaf 3 and Groovy
Jose Juan Montiel
2016-10-09
:jbake-type: post
:jbake-tags: jvm,sprinboot,thymeleaf3,groovy
:jbake-status: draft
:jbake-lang: en
:source-highlighter: prettify
:id: thymeleaf3-groovy
:icons: font

== Groovy

La primera vez que hoy hablar de Groovy fue a finales de 2010, principios de 2011. Yo usaba Freemind para hacer mapas mentales, y por aquel entonces la version 0.9 estaba a punto de salir, con soporte para groovy, ¿que era eso? Llevaba ya algun tiempo usando Freemind, y me dije, si esta gente lo usa, lo mismo sera interesante.

¿Un lenguaje dinamico como Javascript, que podia interactuar con los mapas mentales, haciendolos dinamicos tambien? ¿Crear nodos, relaciones entre ellos, de una manera dinamica?. Lo probe he hice algunas cositas, un script que recopilaba lo tickect de fogbugz y me los mostaba dibujados como nodos del mapa mental.

== Thymeleaf

Thymeleaf es un sistema de templating de servidor, tanto web como standalone. Y su principal objetivo es facilitar

El objetivo principal de thymeleaf es llevar a su flujo de trabajo de desarrollo un sistema de plantillas (no estrictamente HTML), natural y elegante que puede visualizarse correctamente en los navegadores y también funciona como prototipos estáticos, lo que permite una colaboración más estrecha en los equipos de desarrollo.

Con módulos de Spring Framework, una serie de integraciones con sus herramientas favoritas, y la capacidad de conectar su propia funcionalidad, thymeleaf es ideal para el día de hoy en el desarrollo web HTML5 JVM - aunque hay mucho más que puede hacer.

== ¿Porque no mezclarlo?

Una de las caracteristicas nuevas de thymeleaf 3, es que todavia desacoplan mas el diseño del HTML del binding de datos.

En este [link https://github.com/thymeleaf/thymeleaf/issues/465] cuentan como funciona.

La idea es, si puedo escribir cosas del tipo 

<!DOCTYPE html>
<html>
  <body>
    <table id="usersTable">
      <tr>
        <td class="username">Jeremy Grapefruit</td>
        <td class="usertype">Normal User</td>
      </tr>
      <tr>
        <td class="username">Alice Watermelon</td>
        <td class="usertype">Administrator</td>
      </tr>
    </table>
  </body>
</html>

<?xml version="1.0"?>
<thlogic>
  <attr sel="#usersTable" th:remove="all-but-first">
    <attr sel="/tr[0]" th:each="user : ${users}">
      <attr sel="td.username" th:text="${user.name}" />
      <attr sel="td.usertype" th:text="#{|user.type.${user.type}|}" />
    </attr>
  </attr>
</thlogic>

porque no escribirlo en groovy
	
thlogic {
    attr(sel:'#usersTable', 'th:remove':'all-but-first') {
        attr(sel:'/tr[0]', 'th:each':'user : ${users}') {
            attr(sel:'td.username', 'th:text':'${user.name}')
            attr(sel:'td.usertype', 'th:text':'${user.type}')
        }
    }
}

Aqui esta explicacion en el foro de thymeleaf: http://forum.thymeleaf.org/Thymeleaf-and-groovy-td4029599.html

Si aprovechamos este dinamismo, ¿porque no podriamos pensar en un diseño web que pueda ser mas dinamico? ¿Generacion de formularios con un par de lineas? ¿Mostrar datos del modelo con un par de lineas?




== Porque el objetivo final seria poder hacer una aplicacion web que llevara de un rest a la capa de presentacion

https://github.com/josejuanmontiel/dynamic-rest-template

En este proyecto monte un ejemplo de uso de thymeleaf 3, en un proyecto springboot con groovy como lenguaje principal

== Y tambien, que se pudieran inyectar los datos de prueba de manera facil para los test de presentacion...

https://twitter.com/nicolas_frankel/status/760441910272135168

Imaginemos que de alguna manera... a esto

thlogic {
    attr(sel:'#usersTable', 'th:remove':'all-but-first') {
        attr(sel:'/tr[0]', 'th:each':'user : ${users}') {
            attr(sel:'td.username', 'th:text':'${user.name}')
            attr(sel:'td.usertype', 'th:text':'${user.type}')
        }
    }
}

podemos evolucionarlo a 

thlogic {
	users{
		user1:admin,
		user2:editor...
	}
    attr(sel:'#usersTable', 'th:remove':'all-but-first') {
        attr(sel:'/tr[0]', 'th:each':'user : ${users}') {
            attr(sel:'td.username', 'th:text':'${user.name}')
            attr(sel:'td.usertype', 'th:text':'${user.type}')
        }
    }
}

== Jitpack

Asi que lo primero era probar jitpack para meter en una libreria las partes comunes.. dinamic-rest-template

== Este seria el proyecto que las usa

https://github.com/josejuanmontiel/adorable-avatar
	maven { url "https://jitpack.io" }
	compile 'com.github.josejuanmontiel:dynamic-rest-template:-SNAPSHOT'

== Charla: Thymeleaf para maquetadores.

* https://github.com/josejuanmontiel/charla_gradle[Gradle]
* https://github.com/josejuanmontiel/thymeleaf_talk[Thymeleaf]
	http://forum.thymeleaf.org/Thymeleaf-and-groovy-td4029599.html
	https://twitter.com/nicolas_frankel/status/760441910272135168

