= Thymeleaf 3 and Groovy
Jose Juan Montiel
2016-10-09
:jbake-type: post
:jbake-tags: jvm,sprinboot,thymeleaf3,groovy
:jbake-status: draft
:jbake-lang: en
:source-highlighter: prettify
:id: thymeleaf3-groovy
:icons: font

== Groovy

La primera vez que hoy hablar de groovy fue a finales de 2010, principios de 2011. Yo usaba Freemind para hacer mapas mentales, y por aquel entonces la version 0.9 estaba a punto de salir, con soporte para groovy, ¿que era eso?

¿Un lenguaje dinamico como Javascript, que podia poner en el nodo de mi mapa mental para que hicera algo? Lo probe he hice algunas cositas, como un script que recopilaba lo tickect de fogbugz y me los mostaba dibujado como nodos del mapa mental.

== Thymeleaf

Thymeleaf is a modern server-side Java template engine for both web and standalone environments.

Thymeleaf's main goal is to bring elegant natural templates to your development workflow — HTML that can be correctly displayed in browsers and also work as static prototypes, allowing for stronger collaboration in development teams.

With modules for Spring Framework, a host of integrations with your favourite tools, and the ability to plug in your own functionality, Thymeleaf is ideal for modern-day HTML5 JVM web development — although there is much more it can do.

== ¿Porque no mezclarlo?

Una de las caracteristicas nuevas de thymeleaf 3, es que todavia desacoplan mas el diseño del HTML del binding de datos.

https://github.com/thymeleaf/thymeleaf/issues/465

La idea es, si puedo escribir cosas del tipo 

<!DOCTYPE html>
<html>
  <body>
    <table id="usersTable">
      <tr>
        <td class="username">Jeremy Grapefruit</td>
        <td class="usertype">Normal User</td>
      </tr>
      <tr>
        <td class="username">Alice Watermelon</td>
        <td class="usertype">Administrator</td>
      </tr>
    </table>
  </body>
</html>

<?xml version="1.0"?>
<thlogic>
  <attr sel="#usersTable" th:remove="all-but-first">
    <attr sel="/tr[0]" th:each="user : ${users}">
      <attr sel="td.username" th:text="${user.name}" />
      <attr sel="td.usertype" th:text="#{|user.type.${user.type}|}" />
    </attr>
  </attr>
</thlogic>

porque no escribirlo en groovy
	
thlogic {
    attr(sel:'#usersTable', 'th:remove':'all-but-first') {
        attr(sel:'/tr[0]', 'th:each':'user : ${users}') {
            attr(sel:'td.username', 'th:text':'${user.name}')
            attr(sel:'td.usertype', 'th:text':'${user.type}')
        }
    }
}

Aqui esta explicacion en el foro de thymeleaf: http://forum.thymeleaf.org/Thymeleaf-and-groovy-td4029599.html

Si aprovechamos este dinamismo, ¿porque no podriamos pensar en un diseño web que pueda ser mas dinamico? ¿Generacion de formularios con un par de lineas? ¿Mostrar datos del modelo con un par de lineas?

== Porque el objetivo final seria poder hacer una aplicacion web que llevara de un rest a la capa de presentacion

https://github.com/josejuanmontiel/dynamic-rest-template

En este proyecto monte un ejemplo de uso de thymeleaf 3, en un proyecto springboot con groovy como lenguaje principal

== Y tambien, que se pudieran inyectar los datos de prueba de manera facil para los test de presentacion...

https://twitter.com/nicolas_frankel/status/760441910272135168

Imaginemos que de alguna manera... a esto

thlogic {
    attr(sel:'#usersTable', 'th:remove':'all-but-first') {
        attr(sel:'/tr[0]', 'th:each':'user : ${users}') {
            attr(sel:'td.username', 'th:text':'${user.name}')
            attr(sel:'td.usertype', 'th:text':'${user.type}')
        }
    }
}

podemos evolucionarlo a 

thlogic {
	users{
		user1:admin,
		user2:editor...
	}
    attr(sel:'#usersTable', 'th:remove':'all-but-first') {
        attr(sel:'/tr[0]', 'th:each':'user : ${users}') {
            attr(sel:'td.username', 'th:text':'${user.name}')
            attr(sel:'td.usertype', 'th:text':'${user.type}')
        }
    }
}

== Jitpack

Asi que lo primero era probar jitpack para meter en una libreria las partes comunes.. dinamic-rest-template

== Este seria el proyecto que las usa

https://github.com/josejuanmontiel/adorable-avatar
	maven { url "https://jitpack.io" }
	compile 'com.github.josejuanmontiel:dynamic-rest-template:-SNAPSHOT'

== Charla: Thymeleaf para maquetadores.

* https://github.com/josejuanmontiel/charla_gradle[Gradle]
* https://github.com/josejuanmontiel/thymeleaf_talk[Thymeleaf]
	http://forum.thymeleaf.org/Thymeleaf-and-groovy-td4029599.html
	https://twitter.com/nicolas_frankel/status/760441910272135168

