= Retrolambda and default methods
Jose Juan Montiel
2016-10-16
:jbake-type: post
:jbake-tags: jvm,retrolambda
:jbake-status: draft
:jbake-lang: es
:source-highlighter: prettify
:id: retrolambda
:icons: font

== Retrolambda

Este proyecto, solo se puede compilar con la JDK8, porque usa intensamente sus caracteristicas.
https://code.onehippo.org/cms-community/hippo-cms 

Gracias a retrolambda, muchos proyectos que hacen uso de las lambdas de JDK8 pueden migrarse a JDK17 y android.
https://github.com/orfjackal/retrolambda

Y con este pluging maven podrias integrarlo en tu buildsystem
https://github.com/orfjackal/retrolambda#maven-plugin

Aqui un ejemplo
https://github.com/orfjackal/retrolambda/blob/master/end-to-end-tests/pom.xml

Pero hay unas limitaciones bien conocidas, los default method de jdk8 no son tan faciles de portar
https://github.com/orfjackal/retrolambda#known-limitations

Y por defecto vienen deshabilitada su migracion
http://orfjackal.github.io/retrolambda/retrolambda-maven-plugin/process-main-mojo.html

Y creo que este pull request podria ayudar
https://github.com/orfjackal/retrolambda/pull/101

Pero no tengo claro que este sea mi problema con el caso de hippocms, y no sea mas bien la propia limitacion...
https://github.com/orfjackal/retrolambda/issues/56
https://github.com/orfjackal/retrolambda/issues/58




Si lo que has usado son APIs de JDK como las de streaming..
https://sourceforge.net/projects/streamsupport/

Aqui un poco de historia
https://en.wikipedia.org/wiki/Java_backporting_tools 

Aqui unos apuntes sobre el Lifecycle de de maven
https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Setting_Up_Your_Project_to_Use_the_Build_Lifecycle

Y aqui sobre el classloading
http://maven.apache.org/guides/mini/guide-maven-classloading.html


TODO: 
	Explicacion de los default methods.
		- https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html
		- https://dzone.com/articles/interface-default-methods-java 
		- https://blog.idrsolutions.com/2015/01/java-8-default-methods-explained-5-minutes/

	export DEFAULT_METHODS=2 ??? https://github.com/orfjackal/retrolambda/issues/31
	https://github.com/orfjackal/retrolambda/issues/56 ???

	Optionally also: https://github.com/orfjackal/retrolambda#backported-language-features

		Default methods are backported by copying the default methods to a companion class (interface name + "$") as static methods, 
		replacing the default methods in the interface with abstract methods, and by adding the necessary method implementations to 
		all classes which implement that interface.

		Static methods on interfaces are backported by moving the static methods to a companion class (interface name + "$"), 
		and by changing all methods calls to call the new method location.[1]

		[1] The static methods are moved to a companion class even with default method support disabled, because some of them may be 
		lambda implementation methods, but the method calls to static methods are not updated. This may cause weird error messages if
		static methods on interfaces are accidentally used without enabling default method support.

	- http://stackoverflow.com/questions/31160831/android-groovy-android-annotation

