= Retrolambda and default methods
Jose Juan Montiel
2016-10-19
:jbake-type: post
:jbake-tags: jvm,retrolambda,hippocms,android,apt
:jbake-status: published
:jbake-lang: es
:source-highlighter: prettify
:id: retrolambda-and-hippocms
:icons: font

== Retrolambda e Hippo Cms

https://code.onehippo.org/cms-community/hippo-cms[Este proyecto], solo se puede compilar con la JDK 8, ya que hace uso intensivo de sus caracteristicas: lambdas, default methods y otras mas.

Gracias a https://github.com/orfjackal/retrolambda[Retrolambda], muchos proyectos que hacen uso de las nuevas caracteristicas de JDK 8 pueden migrarse a JDK7 (y anteriores) y por tanto tambien a Android, lugar donde se hace principal uso de esta herramienta.

Y con https://github.com/orfjackal/retrolambda#maven-plugin[este pluging maven] puedes integrarlo en tu buildsystem. https://github.com/orfjackal/retrolambda/blob/master/end-to-end-tests/pom.xml[Aqui] un ejemplo de como usarlo. Y ademas, hay otro https://github.com/evant/gradle-retrolambda[para gradle].

== Limitaciones

Pero hay unas https://github.com/orfjackal/retrolambda#known-limitations[limitaciones bien conocidas], que hacen que la migracion de los default method de JDK 8 no sean tan faciles, "must to be backported together, with one execution of Retrolambda".

Por eso, http://orfjackal.github.io/retrolambda/retrolambda-maven-plugin/process-main-mojo.html[por defecto], viene deshabilitada su migracion.

Cuando Retrolmambda migra las https://github.com/orfjackal/retrolambda#backported-language-features[Default Methods]:
Default methods are backported by copying the default methods to a companion class (interface name + "$") as static methods, replacing the default methods in the interface with abstract methods, and by adding the necessary method implementations to all classes which implement that interface.


== Retrolambda (e HippoCms)

Tomemos como ejemplo, https://code.onehippo.org/cms-community/hippo-cms[el siguiente] proyecto.

Supongamos que en un primer modulo tenemos esta interfaz con el default method.

[source,java]
----
public interface IconProvider extends IClusterable {
	default Component getIcon(final String id, IconSize size) {
		return null;
	}
}
----

Retrolambda lo que hace con esta clase es transformarla en esta otra.

[source,java]
----
public abstract interface IconProvider2 extends IClusterable {
  public abstract Component getIcon(String paramString, IconSize paramIconSize);
}
----

E implementa ese metodo (a traves de la "companion class") en las clases que implementen la interfaz, de las clases del mismo modulo.

Por tanto, si no procesa todas las clases hijas de esa interfaz en la pasada del modulo, ya no lo hara, por lo que...

[source,java]
----
public class SearchingSectionPlugin extends RenderPlugin implements IBrowserSection
----

que esta en otro modulo, al intentar ser compilada da este error

[source,java]
----
[ERROR] /hippo-cms/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/SearchingSectionPlugin.java:[63,7] 
	error: SearchingSectionPlugin is not abstract and does not override abstract method getIcon(String,IconSize) in IconProvider
----

== Primeras conclusiones

En un primer momento, sin leer bien el mensaje de error, y sin comprender la jerarquia de clases del proyecto, pense que https://github.com/orfjackal/retrolambda/pull/101[este pull request podria ayudar]

Por si quieres entender mas en detalle, https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Setting_Up_Your_Project_to_Use_the_Build_Lifecycle[aqui] unos apuntes sobre el Lifecycle de de maven. Y http://maven.apache.org/guides/mini/guide-maven-classloading.html[aqui] sobre el classloading.

Luego, leyendo mas en detalle, pense que el problema era que al tranformar la interfaz a abstracta... bueno, que me habia despistado del problema real, y a ese despiste constituyo ver, en https://twitter.com/nicolas_frankel/status/786202575150407680[este tweet] porque https://stackoverflow.com/questions/7202616/java-abstract-interface/7202659#7202659[las interfaces interfaces son abstractas (por defecto)].

Y el propio https://twitter.com/orfjackal[Esko Luontola] nos explica el motivo: "pre-Java 8 JVMs support only abstract methods in interfaces (the <clinit> method being an exception). Retrolambda inserts the default method code to all implementing classes, thus emulating what JVM 8 does."

https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html[Aqui] una explicacion mas detallada de como funcionan los Default Methods en JDK 8. Y https://docs.oracle.com/javase/tutorial/java/IandI/abstract.html[aqui] la explicación de oracle sobre "abstract".

== Explicacion del problema real

Pero el problema, en este caso, era simplemente la limitacion de la libreria en projectos multi modulo https://github.com/orfjackal/retrolambda/issues/56[aqui] y 
https://github.com/orfjackal/retrolambda/issues/58[aqui] lo comentan tambien en detalle.

Una manera de resolverlo, haciendo pequeñas modificaciones en el codigo, seria implementando el metodo getIcon(String,IconSize) con el comportamiento por default en las clases del segundo modulo.

[source,bash]
----
diff --git a/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/BrowsingSectionPlugin.java b/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/BrowsingSectionPlugin.java
index 99bdb0e..9b34ce1 100644
--- a/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/BrowsingSectionPlugin.java
+++ b/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/BrowsingSectionPlugin.java
@@ -18,6 +18,7 @@
 import javax.jcr.Node;
 import javax.jcr.RepositoryException;
 
+import org.apache.wicket.Component;
 import org.apache.wicket.model.IModel;
 import org.apache.wicket.request.resource.ResourceReference;
 import org.hippoecm.frontend.l10n.ResourceBundleModel;
@@ -144,4 +145,10 @@
         return null;
     }
 
+    @Override
+    public Component getIcon(String id, IconSize size) {
+    	return null;
+    }
+    
+    
 }
diff --git a/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/SearchingSectionPlugin.java b/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/SearchingSectionPlugin.java
index 450712b..9d09210 100644
--- a/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/SearchingSectionPlugin.java
+++ b/perspectives/src/main/java/org/hippoecm/frontend/plugins/cms/browse/section/SearchingSectionPlugin.java
@@ -56,6 +56,7 @@
 import org.hippoecm.frontend.service.IconSize;
 import org.hippoecm.frontend.service.render.RenderPlugin;
 import org.hippoecm.frontend.skin.Icon;
+import org.hippoecm.frontend.skin.IconProvider;
 import org.hippoecm.repository.api.HippoNodeType;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
@@ -337,6 +338,11 @@
     public ResourceReference getIcon(IconSize type) {
         return null;
     }
+    
+    @Override
+    public Component getIcon(String id, IconSize size) {
+    	return null;
+    }
 
     private boolean hasSearchResult() {
         return collection.getType() == DocumentCollectionType.SEARCHRESULT;

----

== ¿Proximos pasos?

https://github.com/teras[Teras] y https://github.com/orfjackal[Orfjackal], ¿porque el PR 101 no modifica estas clases para hacer ese cambio? ¿Quizas no lo hace porque ya existe un metodo con ese nombre, aunque no con el mismo numero de paramtros?

== ¿Y que pasa con la compilacion retrolambda de hippocms?

Aun nos quedaba algun error por resolver... metodo estaticos...

[source,bash]
----
[ERROR] hippo-cms/workflow/frontend/src/main/java/org/hippoecm/frontend/plugins/reviewedactions/list/ReviewedActionsListColumnProviderPlugin.java:[72,38] error: cannot find symbol
[ERROR] symbol:   method of(Calendar)
[ERROR] location: interface DateTimePrinter
[ERROR] hippo-cms/workflow/frontend/src/main/java/org/hippoecm/frontend/plugins/reviewedactions/list/ReviewedActionsListColumnProviderPlugin.java:[79,38] error: cannot find symbol
[ERROR] symbol:   method of(Calendar)
[ERROR] location: interface DateTimePrinter
----

Static methods on interfaces are backported by moving the static methods to a companion class (interface name + "$"), and by changing all methods calls to call the new method location.[1]

En este caso la solucion temporal es cambiar los import en las clases del segundo modulo, a la clase companion.

[source,bash]
----
diff --git a/workflow/frontend/src/main/java/org/hippoecm/frontend/plugins/reviewedactions/RequestsView.java b/workflow/frontend/src/main/java/org/hippoecm/frontend/plugins/reviewedactions/RequestsView.java
index 5a97066..ab938b7 100644
--- a/workflow/frontend/src/main/java/org/hippoecm/frontend/plugins/reviewedactions/RequestsView.java
+++ b/workflow/frontend/src/main/java/org/hippoecm/frontend/plugins/reviewedactions/RequestsView.java
@@ -41,7 +41,7 @@
 import org.hippoecm.frontend.plugin.IPluginContext;
 import org.hippoecm.frontend.plugins.reviewedactions.model.Request;
 import org.hippoecm.frontend.plugins.reviewedactions.model.RequestModel;
-import org.hippoecm.frontend.plugins.standards.datetime.DateTimePrinter;
+import org.hippoecm.frontend.plugins.standards.datetime.DateTimePrinter$;
 import org.hippoecm.frontend.plugins.standards.icon.HippoIcon;
 import org.hippoecm.frontend.session.UserSession;
 import org.hippoecm.frontend.skin.Icon;
@@ -110,7 +110,7 @@
                 String state = request.getState();
 
                 final String parameter = schedule != null ?
-                        DateTimePrinter.of(schedule).appendDST().print(FormatStyle.FULL) : "??";
+                        DateTimePrinter$.of(schedule).appendDST().print(FormatStyle.FULL) : "??";
                 return new StringResourceModel("state-" + state, this, null, "unknown", parameter);
             }
----

== Notas finales

Si lo que has usado en tu proyecto con JDK 8 son las APIs de streaming, puedes usar https://sourceforge.net/projects/streamsupport/[esto].

Aqui un https://en.wikipedia.org/wiki/Java_backporting_tools[poco de historia].

== Bola extra

http://stackoverflow.com/questions/31160831/android-groovy-android-annotation[Groovy Android y APT]