= Reflexion sobre el momento actual
Jose Juan Montiel
2022-02-25
:jbake-type: post
:jbake-tags: life, work, ikigai
:jbake-status: published
:jbake-lang: es
:source-highlighter: prettify
:id: donde-te-ves-3
:icons: font

== Ahora hagamos zoom en los ultimo años...

Se podría decir (aunque no todos piensen igual) que he tenido la suerte de estar los últimos 3 años en el mismo proyecto. Y eso, es mucho, mucho tiempo.

Por un lado agradecer a los responsables los esfuerzos realizados, por mantener al cliente contento, y por tanto mantenerlo todo este tiempo, dentro de unos costes mas o menos ajustados... y gracias a estar esos casi 3 años en producción, haber aprendiendo a mantener la rueda girando.

Al final, esta guay montar las cosas desde cero, y echarlas a andar, pero lo que mola de verdad, es mantenerlas andando en PRODUCCIÓN, dando el servicio para el que fueron creadas y ademas, evolucionando mientras todo sigue levantado.

Y si ademas, tienes la suerte de tener un grupo con ganas de aprender, pues... ¿que mas se puede pedir?

A esta altura te preguntaras donde puedes ver todas estas reflexiones... recuerda depende de ti ;)

== ¿Pero quieres saber que es lo proximo... y lo ultimo?
...pues ya sabes donde seguir leyendo https://josejuanmontiel.github.io/blog/2022/03/donde-te-ves-part4.es.html[la siguiente entrada del blog] para ver...
