= 多Donde te ves a los 50 a単os, laboralmente? 
Jose Juan Montiel
2022-02-11
:jbake-type: post
:jbake-tags: life, work, ikigai
:jbake-status: draft
:jbake-lang: es
:source-highlighter: prettify
:id: donde-te-ves-1
:icons: font

== 多Como vas a organizarlo?
=== Lo importante es escribrilo
Y que mejor manera que retomar el blog, para volver a organizar las ideas

=== Aprovechar para usar cosas que queria probar
El blog serviara para ir explicando, pero el resultado final aprovechare para que quede en la pagina princial...

* En la pagina principal tendremos el inicio donde, linkaremos a un conjunto de paginas estaticas organizadas

* Pero como queria probar Ebiten para juegos 2D y WebAssembly habra un link a un juego donde se contara lo mismo, pero de una forma mas interactiva
** El juego arrancara con un Outrun recorriendo una carretera y cogiendo trozos de historia

* Como tambien queria jugar con "criptografia" de andar por casa, vere como hacer para que las respuestas (cifradas) vayan desbloqueando otras respuestas
** Para ello jugaremos con conexiones http a partes de la web que contendran... 

=== 多Plantear un "moldable" para "organizar" tus ideas?
Enlazar con las ideas, modelos... para "red"...

=== Paginas estaticas (indice)
* Reflexion sobre el pasado (parte 2)
* Reflexion sobre el momento actual
* Reflexion sobre el futuro