= Reflexionemos sobre lo pasado 
Jose Juan Montiel
2022-02-18
:jbake-type: post
:jbake-tags: life, work, ikigai
:jbake-status: published
:jbake-lang: es
:source-highlighter: prettify
:id: donde-te-ves-2
:icons: font

== Tras unos 20 años trabajando en este mundo...

Primero toca es mirar atrás... ya es mucho tiempo trabajando... y alguno mas estudiando para llegar al punto profesional donde estoy ahora. Y mas atrás, interesado desde pequeño por el mundo de la informática, gracias a la influencia de mi tio.

Y esto se puede hacer de muchas formas, una posible: pues con una linea temporal, echando mano de la memoria, intentando anotar los hitos de distinta indole que marcaron mi trayectoria. Porque tengamos en cuenta, que no solo lo laboral, afecta al resultado. Al final, aunque hay que mantener separado el trabajo de la vida familiar, una cosa termina afectando a la otra.

Asi que, dibujemos esa linea, marquemos los puntos de inflexión, hagamos un repaso sobre:
* Los empleos por los que he pasado, y las principales tecnologías, he hitos conseguidos.
* Veamos en cuales de ellos he dado un salto cualitativo en mi aprendizaje.
* Y cuando he podido enseñar a gente (mas joven o no) ciertas cosas que los hizo crecer a ellos.
* En cuales, estuve destinado a cliente y mi tareas era, obedecer, hacer lo que otros indicaran.
* Y por ultimo, cuando algún hito familiar, me hizo replantearme ciertas cosas.

Con este repaso, que sera mas o menos extenso, según llegues a el (recuerda que el camino depende de ti) podrás hacerte una idea mas o menos detallada, de como mi reflexión ha conseguido que yo vea lo que dejo atrás, para pensar en el momento en el que estoy (y eso me de paso a ¿donde me veo a los 50?)

== ¿Listo para continuar en mis reflexiones?
...pues ya sabes donde seguir leyendo https://josejuanmontiel.github.io/blog/2022/02/donde-te-ves-part3.es.html[la siguiente entrada del blog] para ver...