= ¿Donde te ves a los 50 años, laboralmente? 
Jose Juan Montiel
2022-02-11
:jbake-type: post
:jbake-tags: life, work, ikigai
:jbake-status: published
:jbake-lang: es
:source-highlighter: prettify
:id: donde-te-ves-1
:icons: font

== El tiempo pasa...
...y me voy a tomar el mio, el que sea necesario, para reflexionar un poco.

Hace mucho, que la vida, eso que sucede mientras nosotros intentamos hacer otras cosas, no me ha permitido pararme a escribir un poco aquí.

Si, es un blog, con perfil técnico, y no hablare (mucho) de cosas que no sean técnicas, pero, si que tengo que reconocer que estos últimos tres años, entre blockchain y golang, no me ha quedado mucho tiempo libre... y bueno, entre mis hijas que se hacen mayores, la familia, el ocio, con la caravana, el bricolage en casa y como no, la pandemia :) pues, al final se mezcla un poco todo.

== ¿Como vas a organizarlo?
Voy a empezar una serie de entradas en este blog, en las que voy a contar como quiero hacer un repaso de mi carrera profesional, y contaré como lo voy a reflejar en la raíz de este sitio (fuera del blog).

=== Lo importante es escribirlo
La mente esta siempre en marcha, escribir obliga a parar y reflexionar mejor sobre lo que quieres plasmar, y esa retro alimentación perfila las ideas, las pule, y asi consigues una vision organizada de las mismas, o esa es la teoría.

=== Aprovechar para usar cosas que quería probar
Y bueno, podría limitarme a escribirlo en un papel, pero el hecho de compartirlo, le añade un punto, que hace que tengas que reflexionar mas seriamente... y ya que te pones, ¿porque no aprovechar para acompañar esas reflexiones con la adquisición de conocimiento nuevo?

Es como suelen decir los que preparan conferencias, el tener que prepararte para contarlo a los demás, hace que uno mismo lo aprenda mejor. Aquí pasa algo parecido, el añadirle nuevos conocimientos, hace que tengas te fuerces a aprenderlo bien, además de organizar las ideas mejor.

Eso si, os contare que hare, y vosotros (si os apetece) lo iréis descubriendo por vuestra cuenta.

==== Manos a la obra
Desde hace un tiempo, quería darle una prueba a https://ebiten.org[Ebiten]: un framework de juegos 2D en Golang. Ciclo de refresco, siempre me llamo la atención en
los juegos. De hecho, hace 3 años iba con mi hija mayor a clases de percusión, y como me costaba mucho coordinar los golpes al son del metronomo, pense hacer un juego 
(usando en este caso https://litiengine.com[Litiengine], Java en este caso) para con la ayuda de un buen micro, detectar los golpes y hacer que un "Mario" saltara para golpear con la cabeza unas cajas sordas, que se movían por la pantalla al ritmo de 4/4 (la idea quedo en el baúl, con tantas otras).

Y bueno, como en GoLang (como en otros lenguajes) se puede compilar en WebAssembly, ¿porque no aprovechar y colocar el juego (aun no he dicho cual, tendrás que descubrirlo) en la web, y hacer que con su ayuda, vaya contando mi historia?

=== Próximas secciones
Pues la idea es simple, para conseguir encontrar el Ikigai del programador... 

* Reflexión sobre el pasado...
...desde mis orígenes: mis primeros pinitos (tardíos) con la informática... hasta llegar a hace unos años.

* Reflexión sobre el momento actual...
...que incluye los últimos 3 años aproximadamente.

* Reflexión sobre el futuro...
...retomando el objetivo del titulo de esta entrada... ¿donde me veo con 50 años? Es una pregunta que hice a varios compañeros, cuando cumplí los 40. La idea era reflexionar sobre donde queria estar, y que tenia que hacer para llegar ahi. Pero, llego la pandemia y seguimos tirando. Asi que...

=== ¿Listo para ver el resultado?
¿Quieres ver primero https://josejuanmontiel.github.io[**el resultado final**]... o continuas leyendo https://josejuanmontiel.github.io/blog/2022/02/donde-te-ves-part2.es.html[la siguiente entrada del blog] para descubrir mas detalles?