= Reflexionemos sobre lo pasado 
Jose Juan Montiel
2022-02-18
:jbake-type: post
:jbake-tags: life, work, ikigai
:jbake-status: published
:jbake-lang: es
:source-highlighter: prettify
:id: donde-te-ves-2
:icons: font

== Tras unos 20 años trabajando en este mundo...

Pues como ya hemos comentado, ahora en esta fase lo que toca es mirar atras... ya son 20 años trabajando... y unos cuantos mas estudiando para llegar al punto profesional donde estoy ahora. Y mas atras, interesado desde pequeño por el mundo de la informatica, gracias a la influencia de mi tio.

Y esto se puede hacer de muchas formas, una posible: pues con una linea temporal, echando mano de la memoria, intentando marcar los distintos hitos de distinta indole que marcaron mi trayectoria. Porque tengamos en cuenta, que no solo lo laboral, afecta a lo laboral. Al final, aunque hay que manetener separado el trabajo de la vida familar, una cosa termina afectando a la otra.

Asi que, dibujemos esa linea, marquemos los puntos de inflexion, hagamos un repaso sobre:
* Los empleos por los que he pasado, y las principales tecnologias, he hitos conseguidos.
* Veamos en cuales de ellos he dado un salto cualitativo en mi aprendizaje.
* Y cuando he podido enseñar a gente (mas joven o no) ciertas cosas que los hizo crecer a ellos.
* En cuales, estuve destinado a cliente y mi tareas era, obedecer, hacer lo que otros indicaran.
* Y por ultimo, cuando algun hito familiar, me hizo replantearme ciertas cosas.

Con este repaso, que sera mas o menos extenso, segun llegues a el (recuerda que el camino depende de ti) podras hacerte una idea mas o menos detallada, de como mi reflexion ha conseguido que yo vea lo que dejo atras, para pensar en el momento en el que estoy (y eso me de paso a ¿donde me veo a los 50?)

== ¿Listo para continuar en mis reflexiones?
...pues ya sabes donde seguir leyendo https://josejuanmontiel.github.io/blog/2022/02/donde-te-ves-3.es.html[la siguiente entrada del blog] para ver...