= Thymeleaf 3 and Groovy
Jose Juan Montiel
2016-10-16
:jbake-type: post
:jbake-tags: jvm,hippocms
:jbake-status: draft
:jbake-lang: en
:source-highlighter: prettify
:id: hippocms
:icons: font

== Gluon OSS

OpenJdk Mobile - http://openjdk.java.net/projects/mobile/

Zero assambler project 	- http://openjdk.java.net/projects/zero/
			- http://icedtea.classpath.org/wiki/ZeroSharkFaq

cross tool chain
	- android - http://openjdk.java.net/projects/mobile/android.html
	- Ojo que tambien ios y windows phone

¿gluon vm?

Compiling with jack - https://source.android.com/source/jack.html

Android vm
	- https://archon-runtime.github.io/
	- kivy 	- https://kivy.org/#home
		- https://kivy.org/docs/guide/android.html

Griffon y basilisk - http://jroller.com/aalmiray/entry/and_griffon_beget_basilisk


Basilisk - https://github.com/basilisk-fw/basilisk


Correo a Jose Pereda.

Hola,

hacia tiempo que no me pasaba... pero entre que la mayor (mi hija de 7 años) esta con toses, y las ideas me bullen en la cabeza, no puedo dormir. Asi que voy a escribir un ladrillo para dejarlo todo ordenado ;)

Lo primero un placer haber asistido al meetup y al workshop, se agradece el esfuerzo aunque no hubiera mucha asistencia...

La verdad es que siempre había tenido en el radar JavaFX aunque no haya hecho profesionalmente nada, lo mas cercano una app de escritorio (hace 3 años) para manejo de "proceso por lotes" que al final fue en swing, y de ahi empece a trastear con android... de hecho hasta di una charla en el MadridGUG http://www.madridgug.com/2014/06/madrid-gug-junio-2014-dropwizard-de.html y finalmente publique mi "app" https://play.google.com/store/apps/details?id=com.accreativos.whatshappening que va a ser la candidata perfecta para la migracion a JavaFX y Gluon.

Eso me lleva al primer punto, a ver si me animo y hago una contribucion a https://bitbucket.org/gluon-oss/charm-down para ver si tiene sentido "modelar el compartir" como servicio dentro de charm-down, vamos el

            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="image/*" />
            </intent-filter>

de android, y el equivalente de ios, que no se como seria... modelar y evolucionar para customizar el tipo de cosas a poder "capturar" en el compartir, procesos internos de unificacion.... y el propio codigo de "captura en la clase android"

        // if this is from the share menu
        if (Intent.ACTION_SEND.equals(action))
        {
            if (extras.containsKey(Intent.EXTRA_STREAM))
            {
                try
                {
                    // Get resource path from intent callee
                    Uri uri = (Uri) extras.getParcelable(Intent.EXTRA_STREAM);

                    // Query gallery for camera picture via
                    // Android ContentResolver interface
                    ContentResolver cr = getContentResolver();
                    InputStream is = cr.openInputStream(uri);

                    mAsyncTaskManager.setupTask(new Task(getResources(), is, uri.getPath()));

                    return;
                } catch (Exception e) {
                    writeMessage(e.toString());
                }
            } else if (extras.containsKey(Intent.EXTRA_TEXT)) {
                return;
            }
        }

Lo dicho con JavaFX, siempre en el punto de mira, y mas desde que asisto a los MadridGUG, tambien vi este meetup http://www.madridgug.com/2016/08/madrid-gug-septiembre-2016-groovy.html y hace poco este https://virtualjug.com/the-javafx-ecosystem/

Lo que me lleva al segundo punto, este mas profesional, estoy metido en un "proyecto" que digamos va a tener una parte de dashboard que lo mismo lo planteo con JavaFX (ya que incluso se puede mezclar con jnlp http://docs.oracle.com/javafx/2/deployment/packaging.htm) ya vere, pero la potencia estaria que ademas tendriamos "gratis (aprovechando el mismo esfuerzo)" las moviles... si sale adelante contactare contigo/gluonhd a nivel profesional.

Pues lo dicho, un placer y gracias.

Seguiremos en contacto.
